From: Pumirer Horukollad
Subject: Defiant as a museum?
To: soc.sol
Message-Id: 6b460e26-b61e-49d8-9912-8c402c09d417

I heard a rumor that they were taking an ancient decommissioned ship and
turning it into some kind of museum. Does anyone know if this is true?
My friend mentioned something about the SS Defiant, which I sorta
remember reading about in school, but I'm a bit fuzzy.



From: Migob Satefin Gobetanum
Subject: Re: Defiant as a museum
To: soc.sol
Message-Id: 8a15c912-edb9-44b2-8793-0a4a1c77d3ae
In-Reply-To: 6b460e26-b61e-49d8-9912-8c402c09d417

I bet they'll be sure to clean up all the evidence of the Defiant's
sabotage if so. Can't have that stuff coming to light!



From: Lusod Petuzun
Subject: Re: Defiant as a museum
To: soc.sol
Message-Id: 9d738117-f2ab-472f-b443-9717b228d03c
In-Reply-To: 6b460e26-b61e-49d8-9912-8c402c09d417

> I heard a rumor that they were taking an ancient decommissioned ship and
> turning it into some kind of museum. Does anyone know if this is true?

Yeah, my cousin is involved in some of the preparations for this. He
says they're going to park it in orbit around Mars and fill it up with
second- and third-colonization-wave artifacts.

It's not the Defiant that they're using, of course--the Defiant is still
floating out in interstellar space, abandoned after the rescue ship
evacuated it. The ship they're preparing is the SS Goddard, which is the
one that was launched to save the survivors and bring the portal they
were carrying back to Sol. Still, the idea of being able to walk around
on one of the ships that were critical in connecting Sol to the portal
network is pretty cool.



From: Degevier Jarkad
Subject: Re: Defiant as a museum
To: soc.sol
Message-Id: c746c55b-9575-4eef-a4fa-17662318fd9f
In-Reply-To: 8a15c912-edb9-44b2-8793-0a4a1c77d3ae

> I bet they'll be sure to clean up all the evidence of the Defiant's
> sabotage if so. Can't have that stuff coming to light!

Will you give this a rest already? Everyone's tired of your conspiracy
theory ravings.
