From: Poudotem Figgouroudozoum
To: soc.sol
Subject: Exploration summit
Message-Id: 0f5f8b74-4695-436d-9a70-2bd75db0fae9
Content-Type: text/plain; charset=UTF-8

The Human Worlds League is holding a Space Exploration summit soon. Any
bets on which nearby systems we'll be launching probes to next? Is it
even possible they'd be planning the launch of a new colony?



From: Touxoxer Befoum
To: soc.sol
Subject: Re: Exploration summit
Message-Id: 9147fd3b-e223-4a62-ab49-1fc831b8a481
In-Reply-To: 0f5f8b74-4695-436d-9a70-2bd75db0fae9
Content-Type: text/plain; charset=UTF-8

> Is it even possible they'd be planning the launch of a new colony?

It seems way to soon--it's only been about 12 megaseconds since the last
colony ship arrived in L 668-21.



From: Ciecog Tiebossur
To: soc.sol
Subject: Re: Exploration summit
Message-Id: 9e3b866f-621b-44d8-a2e4-61738e29aee0
In-Reply-To: 9147fd3b-e223-4a62-ab49-1fc831b8a481
Content-Type: text/plain; charset=UTF-8

> It seems way to soon--it's only been about 12 megaseconds since the last
> colony ship arrived in L 668-21.

I wouldn't rule it out. I mean, L 668-21 was colonized specifically
because of its rich asteroids; it was never intended to grow in
population beyond the minimum required to support mining operations in
the system.
