From: Ricarad Jinod
Subject: [help] Second sensor test
To: soc.tana
Message-Id: e5ecc7c8-2959-4976-a123-239319f0b889
Content-Type: text/plain; charset=UTF-8

I'm a student working on a postdoc degree in astrophysics. I've got an
improved sensor array that has passed through some lab tests and initial
field testing, but it needs a bit more exposure still.

We've determined from the last test that the optimum range is under
3000, not the 5000 in the original specs. The kind of radiation under
study is strongest in the New Phobos system, which is quite a ways from
Mars. You will need to spend a quarter of a kilosecond within range of
the star.

Because of the distance, we are prepared to supply you with a passponder
device to allow you access to New Phobos and the systems on route. The
passponder device may be kept as payment once the mission is completed.
