From: Ricarad Jinod
Subject: [help] Test sensor array
To: soc.tana
Message-Id: fdb7f320-8911-4753-ad8f-3a20260ea7e8
Content-Type: text/plain; charset=UTF-8

I'm a student working on a postdoc degree in astrophysics. I've got an
improved sensor array that has passed through some initial lab tests,
but it needs some real-world testing.

At this point I need someone to load it aboard and fly it around the
Wolf 294 star (in a system adjacent to Tana) in order to get some
readings. It will take a quarter kilosecond of close orbit (within 5000
of the star) in order to complete the measurements we need. Bring the
sensor array back to Mars for analysis.
