From: GNO Maintainers
Subject: [ANN] Orb OS 32.5.0 released
To: comp.os.orb
Content-Type: text/plain; charset=UTF-8
Message-Id: e703a0ab-a7f5-404d-9e16-1eeef4d5dab7

We're happy to annouce the release of Orb 32.5.0.

The highlights for this release include:

* Improved detection of user escalation exploits
* Interpolate environment variables in the shell
* Expand the standard library to include ipairs and unpack

Please note that environment variable interpolation uses ${VAR} instead
of the more traditional (and more ambiguous) $VAR.

About Orb OS

Orb OS is a general-purpose multi-user operating system loosely based on
Unix that respects the user's freedom. Orb is licensed under the Generally
Public License version 12 or later.
