version: 2
jobs:
  build:
    working_directory: ~/bussard
    docker:
      - image: lambdaindie/love2d:latest
    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -qq -y lua-check cloc
      - run: make ci
