From: Mietubum Subam
Subject: What's the deal with gravity?
To: sci.physics
Message-Id: b4cb9f00-71b9-11e5-a3d5-001f16110e8c
Content-Type: text/plain; charset=UTF-8

How is it that the gravitation exerted by an object increases when you
get closer to it? It seems like when you're far away it hardly affects
you at all, but then when you get close all of the sudden it's pretty
intense.



From: Pulout Rounab
Subject: Re: What's the deal with gravity?
To: sci.physics
In-Reply-To: b4cb9f00-71b9-11e5-a3d5-001f16110e8c
Message-Id: ad15220a-596d-46ed-93f1-ac785879d4ef
Content-Type: text/plain; charset=UTF-8

Remember Newton's law of gravitation!

  F = G * (m1 * m2 / r^2)

Distance here is represented by r, so as this increases, the effect of
gravity decreases by its square. This means as soon as you're a good
distance away the effect is essentially negligible.
