.TH BUSSARD 6 "21 June 2016"
.SH NAME
bussard \- a space flight programming adventure
.SH SYNOPSIS
.B bussard
.SH DESCRIPTION
 A space flight programming adventure game. Mine, trade, upgrade, and unlock the potential of your spacecraft by hacking on the code that makes it tick.
.PP
\fBbussard\fP is a graphical game built using Lua and the LOVE
framework. This command executes a bash script of the bussard.love package against the love executable.
.SH OPTIONS
 None.
.SH SEE ALSO
.BR love (1),
.br
.SH AUTHOR
Bussard was written by Phil Hagelberg and other contributors.

