From: Poviet Lassoum
Subject: Aquaponics?
To: soc.tana
Message-Id: 216f9e0c-7e75-4d92-b6ba-1301c6dd135e
Content-Type: text/plain; charset=UTF-8

I keep hearing about how Tana is having a hard time getting enough food
from Sol. I know the colony ships were equipped with their own
aquaponics rigs for the voyage over; are those currently in use? I'm
thinking about buying some more equipment in another system and bringing
it in to set up to help meet the expanding need, but I want to hear from
others doing it.



From: Dumagog Merot Soubad 
Subject: Re: Aquaponics?
To: soc.tana
Content-Type: text/plain; charset=UTF-8
Message-Id: 631cb730-e203-4b82-941e-74ad25c80b96
In-Reply-To: 216f9e0c-7e75-4d92-b6ba-1301c6dd135e

I know a place on Kuchang Station where you can get a good price on the
gear if you decide to go forward with this.
