From: dex19@adahn.local
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(3): a favor
Message-Id: d1f50ba3-9ad7-414e-8cb6-cf30f98ca3ef
In-Reply-To: 995735b0-ae11-4bb4-814f-ce7cb566b70f

She's being salty all right, but to be fair I deserve it.

I wonder what this "Junction" he talks about is. It could be the device that's
in the secondary expansion bay; that looks like it was installed in a hurry
and doesn't resemble any standard equipment I've ever seen on a ship before.

------------------------------------------------------------------------------

> Thanks for playing the Bussard beta!
>
> This is as far as the missions go so far, but keep an eye on the game as it
> progresses; there will be more.
>
> If you have feedback on the game, please leave a comment on
> https://technomancy.itch.io/bussard or open a bug report at
> https://gitlab.com/technomancy/bussard.
