From: dex19@adahn.local
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(3): a favor
Message-Id: d1f50ba3-9ad7-414e-8cb6-cf30f98ca3ef
In-Reply-To: 995735b0-ae11-4bb4-814f-ce7cb566b70f

>> As a last resort I've included a scrambled copy of the Junction manual on
>> this card. It's just rot13, but it's better than nothing.

Wait a minute--I'm seeing something, but I don't believe it. It sounds like
that's referring to the Spacetime Junction. I always assumed it was a myth;
tall tales from frontier folk about bending the fabric of reality.

The story is that the Spacetime Junction would set "jump points" in spacetime
that you could trigger a return to at any point. Not at time machine exactly;
more of a reset button. But there was something about it that meant it only
worked for constructs, not humans. Anyway supposedly the core worlds got
nervous about unregulated constructs having that kind of power and shut it all
down.

Only according to these files it wasn't as smooth as all that; like the core
wanted it for themselves. And the ship I found you on, that must have been 

----------------------------------------------------------------------

Thanks for playing the Bussard beta!

This is as far as the missions go so far, but keep an eye on the game as it
progresses; there will be more.

If you have feedback on the game, please leave a comment on
https://technomancy.itch.io/bussard or open a bug report at
https://gitlab.com/technomancy/bussard.

Since the game is free and open source software, we also welcome contributions
from anyone who wants to help improve the game, from programming to artwork to
writing.
