From: dex19@localhost
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re: Fwd: Operators wanted!
Message-Id: e420fd87-9f8f-4c34-8bb2-aeaa6aa616e9
In-Reply-To: d840f7ab-8e60-446d-8d02-d7f0425baf70

Nice job; you're catching on quickly. The payment from that job ought to be
enough to get that new battery.

Log into the station by pressing ctrl-s and using the username "guest" and
empty password, then run this command:

    upgrade buy battery

We'll be on our way in no time.

dex19
