From: dex19@localhost
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Getting out of here
Message-Id: 3051ee3f-4703-4f57-b330-f8fb1b3ce2bb

Nice job getting the battery. It's about time we got out of here.

Fly over on an intercept course to the portal and try to match its orbital
path. Press ctrl-p to activate the portal and we can start making our way
back to civilization, or something approximating it.

dex19

----------------------------------------------------------------------

Thanks for playing the Bussard beta!

This is as far as the missions go so far, but keep an eye on the game as it
progresses; there will be a lot more.

If you have feedback on the game, please leave a comment on
https://technomancy.itch.io/bussard or open a bug report at
https://gitlab.com/technomancy/bussard.

Since the game is free and open source software, we also welcome contributions
from anyone who wants to help improve the game, from programming to artwork to
writing.
