From: dex19@localhost
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Greetings
Message-Id: 124ced33-46eb-48f8-a3e6-e22e54202336

Oh wow, it looks like you're coming around. I wasn't sure if this was actually
going to work--your craft was not designed for such a long interstellar
trip. You've probably got a lot of questions, but your ship sustained a fair
bit of damage on its trip, and the top priority is getting the backup systems
online so we're in a less precarious situation.

I've been able to log in using the emergency maintenance protocols, but I
don't have access to initiate a reactor restart in order to bring the main
engine back online. I need you to run this function using your console:

    ship.engine.restart()

You can get back to the console by pressing f2. Don't forget to add the
parentheses on the end.

Use ctrl-pageup/pagedown to cycle thru the open buffers. I'll give you further
instructions once the engine is back online; at that point you can press f3 to
go back to the mail listing and then to the inbox.

dex19
