From: dex19@localhost
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Fwd: Operators wanted!
Message-Id: d840f7ab-8e60-446d-8d02-d7f0425baf70
In-Reply-To: 81299ce2-a9a0-43c2-b2d9-77e6fb05b47b

There's not much work available on this station that would be suitable for
the likes of you or me, but I did find this posting from a few weeks back.

Probably worth a shot; I don't see any other way of buying the battery
we need to get out of this system. Log into the station by pressing ctrl-s
when the station is targeted and using the username and password below.

Good luck.

dex19

recruiting@cmec.tana writes:

> Help wanted for bot operations.
>
> This is an entry-level position suitable for humans and constructs. No
> previous experience in mechanical maintenance or programming is required.
> CMEC offers an initial skills training program, after which hires may
> qualify for postings all over the Tana colonies.
>
> In order to sign up for the training program, log in to Merdeka Station with
> the username "trainee" and the password "reindeerflotilla". The training
> will begin once you have connected.
