From: dex19@localhost
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Fwd: Re: a favor
Message-Id: 47856155-9a8a-4a75-8a81-96a7c5cc10c4
In-Reply-To: c6c2c6b2-b661-4bad-94d3-8dee5968d89c

So my friend is ... well ... see for yourself:

> nari.phouen@starlink.net writes:
>
> dex you อาเจียน ลิง, I told you not to contact me. I really don't want to get
> dragged into this.
>
> Listen; I'll see what I can do about your memory card if it gets you out
> of my hair. But I am *not* coming along on whatever scheme you've planned.
>
> I've got a spare short-range rover parked at the Solotogo port; log in as
> "nari02" with "mendanciouspolyglottal" as the password.
>
> Use the code below to transfer the card to the rover, then navigate it up
> to my compound at 42x207. Once I get my hands on the card I'll email you
> the contents.

----------------------------------------------------------------------

Thanks for playing the Bussard beta!

This is as far as the missions go so far, but keep an eye on the game as it
progresses; there will be a lot more.

If you have feedback on the game, please leave a comment on
https://technomancy.itch.io/bussard or open a bug report at
https://gitlab.com/technomancy/bussard.

Since the game is free and open source software, we also welcome contributions
from anyone who wants to help improve the game, from programming to artwork to
writing.
