From: dex19@adahn.local
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re: Greetings
Message-Id: 81299ce2-a9a0-43c2-b2d9-77e6fb05b47b
In-Reply-To: 124ced33-46eb-48f8-a3e6-e22e54202336

All right; I've run a full diagnostic and completed as much repair work as is
realistic at this point. The engines and most of the computer systems are
running.

Of course, you would expect that taking a spontaneous interstellar flight
would result in damage just from interstellar debris and years spent in the
cold void. But not all these failures can be explained that way. The storage
array was flooded with coolant which froze and destroyed most of it, and the
hatch to the onboard repair drone bay was wedged deliberately from outside.
Any logs that could have shed some light on what happened would have been kept
on the storage array, so I don't know if there's much more we can learn from
examining what we have on hand.

On top of that, the temperature has rendered your backup battery's capacity
severely reduced. It's enough to power onboard systems but it's never going to
be able to activate a portal to leave the system. They sell batteries on
Merdeka Station that should be compatible with your ship, but we'll have to
find a way to pay for it... and that could get interesting.

Fly over to the station and I'll see what I can come up with.

dex19
