From: dex19@localhost
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(2): Greetings
Message-Id: 9876ec1c-f065-4bf8-8a8e-314c5e2fe9ca
In-Reply-To: 81299ce2-a9a0-43c2-b2d9-77e6fb05b47b

> Fly over to the station and log in.

Right, so maybe it wasn't quite obvious how to do this; it would probably be
be helpful to go into a bit more detail. Go into flight mode by pressing f1,
then press tab until the station is targeted.

Fly over to it using the arrow keys. Remember that your engine only controls
your acceleration; your actual movement is determined more by gravity and the
momentum you've already got. Keep an eye on the red fuel gauge in the corner,
though the fuel collector will slowly replenish it if you do run out.

You can see your trajectory plotted out as well as the trajectory of your
target, in this case the station. Try to get your trajectories to cross at the
same point. Note that flying towards your target is not always the best way to
reach it since you need to match orbits with it; sometimes it makes more sense
to go around the star and rendezvous on the other side. Establishing a
clockwise orbit when your target is counterclockwise is just going to burn
thru your fuel.

Use the = and - keys to zoom in and out. Once you get within communications
range of the station, your targeting indicator will turn bright green. At that
point you should engage the orbital lock by pressing f4 so you don't drift out
of range. Once you're in range I'll log in and see what I can do.

dex19
