From: dex19@adahn.local
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Fwd: Re: a favor
Message-Id: 47856155-9a8a-4a75-8a81-96a7c5cc10c4
In-Reply-To: c6c2c6b2-b661-4bad-94d3-8dee5968d89c

So my friend is ... well ... see for yourself:

> nim.pattachoti@starlink.net writes:
>
> dex you อาเจียน ลิง, I told you not to contact me. I really don't want to get
> dragged into this.
>
> Listen; I'll see what I can do about your memory card if it gets you out
> of my hair. But I am *not* coming along on whatever scheme you've planned.
>
> I've got a spare short-range rover parked at the Solotogo port; log in as
> "nim02" with "mendaciouspolyglottal" as the password, then navigate it
> to my compound at 40x100. Once I get my hands on the card I'll email you
> the contents.
