From: dex19@adahn.local
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Memory card
Message-Id: 0c5f9e85-13c0-4bcc-ba29-a2cbe9155e81

It's about time we got out of here.

On my first look thru the ship I missed one small detail--behind one of the
hatches was a small memory card. It's an outdated form factor that none of the
remaining systems on this ship can read, but I have an old friend who might be
able to help us.

Disengage the orbital lock by pressing f4, then fly over on an intercept
course to the portal. Press ctrl-p once you're in range of portal. You can use
the orbital lock again if it helps.

On the other side, take the portal to Wolf 294 and fly to Solotogo. Once we
get there I'll see if I can contact them.

dex19
