From: Moubien Wusid
To: captain@adahn.local
Subject: Re: Anyone seen Dorath recently?
Content-Type: text/plain; charset=UTF-8
Message-Id: aa2ab744-7eb0-4da1-bbe9-da913c901dc5

Great. All I know is that he sent a message from Sutep a couple weeks
ago, so that would be a good place to start looking. I'll get you travel
clearance through the Terran Republic and into Bohk for this.



Thanks for playing the Bussard beta!

This is as far as the missions go so far, but keep an eye on the game as it
progresses; there will be a lot more.

If you have feedback on the game, please leave a comment on
https://technomancy.itch.io/bussard or open a bug report at
https://gitlab.com/technomancy/bussard.

Since the game is free and open source software, we also welcome contributions
from anyone who wants to help improve the game, from programming to artwork to
writing.


