From: support@kosaga.com.bohk
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Congratulations on the purchase of your spacecraft
Date: 2372:30,486,891
Message-Id: c692e8cf-f99b-446e-88e0-390909f659a5

Congratulations on the purchase of your Kosaga Shipyards Bussard-class
spacecraft! Your ship is equipped with state of the art components as
well as the capacity to dynamically reconfigure to add new capabilities.

The easiest way to get started is by reading the Quick Start Guide.
Press f2 from flight mode to open the console, and then type this:

    man("quickstart")

At some point you will want to familiarize yourself with the rest of the
workings of your ship. You can read the complete reference manual by
running this in your console:

    man("manual")

Please enjoy your new spacecraft; with care and proper adherence to safety and
maintenance schedules it will serve you reliably. Note that to be eligible for
warranty coverage, your craft must be registered within 2 megaseconds of
purchase.

Sincerely,
Your friends at Kosaga Shipyards
