From: support@kosaga.com.bohk
To: captain@adahn.local
Date: 2372:30,486,891
Content-Type: text/plain; charset=UTF-8
Subject: Congratulations on the purchase of your spacecraft
Message-Id: c692e8cf-f99b-446e-88e0-390909f659a5

Congratulations on the purchase of your Kosaga Shipyards Bussard-class
spacecraft! Your ship is equipped with state of the art components as
well as the capacity to dynamically reconfigure to add new capabilities.

Note that to be eligible for warranty coverage, your craft must be
registered within 2 megaseconds of purchase. While you are advised to
study the detailed manual which is included in your ship's onboard
computer, the following quick start may help you get going.

The flight controls use your helm keyboard's arrow keys; the up key
engages the engines, while left and right activate the turning
thrusters. Use the equals and minus keys to zoom in and out.  Your
ship's safety features will prevent collision with any other ships,
asteroids, stars, etc, so there is no need to fear.

Pressing control-enter opens the ship's editor, which allows you to
interact with the onboard computer. It begins in console mode, which
lets you write code directly, but you can also activate other modes;
most notably opening files to edit by pressing alt-o.

Your ship's onboard computer also contains an SSH client, which allows
you to connect with the port computers at various stations and planets
you may encounter. You can log in by pressing tab to target a world with
a port computer and flying within range (your targeting indicator will
turn bright green when in range) then opening the console and running
"ssh()". This will log you in as a guest, if you have an account with a
username and password you can supply them as arguments to the ssh function.

Finally your ship is also equipped with a mail client, which you can use
to read your own personal mail as well as mail sent to various mailing
lists.

At some point you will want to familiarize yourself with the rest of the
workings of your ship. You can read the complete manual by running this
in your console: man("manual")

Please enjoy your new spacecraft; with care and proper adherence to
safety and maintenance features it will give you gigaseconds of reliable
service.

Your friends at Kosaga Shipyards
