From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(6): Passenger run from Tana Prime to Apkabar Station
Message-Id: c369f9dc-9041-4672-8d0c-b7d28894e20d

Thanks; I'll see if I can track down my friend.

By the way, I took a look at the encrypted files that Strauss mentioned. I take
it you haven't made any progress on deciphering them yet? From what I can tell
you're a bit of a blank slate; not a lot of skills hard-coded in, but a powerful
ability to acquire new skills.

I'm not much of a hacker, but I took a course on programming when I was
fifteen. Most of the files are completely gibberish to me, but I might be able
to help you with one of the files, the one labeled "msg1_rot13".

Let me know by replying to this message if you want some help decrypting it.
