From: nari@starlink.net:
To: dex19@adahn.local
Cc: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(2): a favor
Message-Id: 995735b0-ae11-4bb4-814f-ce7cb566b70f
In-Reply-To: 67b1f706-73e1-47bb-8111-41fafba10334

You're completely mad; you know that, right?

I do not want to know where you found this memory card. But here's the
contents of the file on it. We're even now, so go on and get lost.

-Nari

> So this is it then; I'll probably die in here.
>
> I suppose we should have seen it coming. We suspected they would try to get
> unauthorized access to the lab. We upgraded our intrusion detection systems
> and ran red-team exercises, but we never expected anything like this.
>
> It all happened so fast. The military bots coming in to the campus, the
> lockdown, the realization of why they were here, the mad scuffle to get the
> Junction to the ship where we could get it away.
>
> I think I'm out of immediate danger right now, but my long-term odds of
> survival wouldn't be good even I weren't sharing the ship with a construct
> that wanted me dead.
>
> Time to think, to focus. There's more I can do.
>
> The ship doesn't have enough fuel to turn around and get back to where we
> launched from. But it looks like the way we're traveling now will put us on a
> course for Ross, probably for a planned rendezvous. The last thing I want is
> for the Junction to fall into their hands. I don't need to stop the ship; I
> just need to throw it off course.
>
> Blowing the airlock might do that, especially if I disable the repair
> drone. Getting the ship into a spin might force the remaining fuel to be
> spent righting it. I wouldn't survive it, but I wouldn't survive anyway.
>
> Here we go.
>
> -Strauss
