From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(2): Fwd: Read me and Forgive me
Message-Id: 8c81f12d-2614-4721-9af3-1f29f6354752

Ugh; I forgot about the security checks. Of course you don't have one
for this ship yet, and the panjandrums don't much like that.

If you swing by the station I can probably get us what we need at Apkabar.
