From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(2): Passenger run from Tana Prime to Apkabar Station
Message-Id: 9dbc52c9-1a27-4b75-b2a7-6af019a72e05

OK, just what kind of ท้อง เสีย ช้าง are you trying to pull here? I've been
nopping in the promenade for a few ksecs; I figure to kill a little time
I'd scan your ship to see what's up--that's when I found out there were
no life forms on board.

You think I'm going to fall for your scam, whatever it is? You must know
it's illegal for un-manned ships to travel interstellar routes. People
call me paranoid for wanting to see a bloke face-to-face before
boarding, but I'd say today it's pretty justified!
