From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(6): Passenger run from Tana Prime to Apkabar Station
Message-Id: 7b5ad7aa-34b4-47df-8573-f9ef55c56d0b

Thanks; I'll see if I can track down my friend.



Thanks for playing the Bussard beta!

This is as far as the missions go so far, but keep an eye on the game as
it progresses; there will be a lot more.
