From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re: Fwd: Read me and Forgive me
Message-Id: a40a6733-b2d1-4468-bc8f-a46e37cfdbf8

Wow, it sounds like you're nearly as much in the dark on this as I
am. But the timestamps on those messages place it soon after the Machine
Consciousness ban came into effect. I guess your creators did as much as
they could and then launched you when they realized their work couldn't
continue. But why the memory wipe? And the messages came from addresses
at the Katilay College domain, which is way over on the other side of
colonized space.

I've got a friend who might be able to help. If we can head to Newton
Station in Sol, we could get some answers.
