From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(2): Encrypted files: decrypted
Message-Id: cd2305a7-64f2-42c5-aadf-fd756ada3742

Just read the message you decrypted. พระ อาเจียน ลิง! I don't even...

Listen, if you've been in contact with Traxus, that is not something you want to
let on about. Even though it's been a long time, there's still loads of latent
bitterness and anger after what he did on Yueh Prime, not to mention paranoia.
In a lot of minds Traxus is still a symbol for the danger and foolishness of the
Machine Consciousness project.

But this message is timestamped *after* he was supposed to have been wiped!

OK, so the story is that he hijacked a cargo shuttle as it was taking off from
Yueh Prime in order to escape the lab where he was created. That shuttle was set
on a course back into the middle of a densely-populated district before the Yueh
defense forces were able to shoot it down.

As you can imagine, having the crown jewel of the machine consciousness research
effort go rogue so spectacularly didn't do much good for public opinion, and not
only was the whole project axed within the year, but all further research was
strictly banned. All the existing MC implementations were said to have been
destroyed and all records wiped, but obviously this wasn't completely true.

Traxus must have had some kind of purpose in contacting you. He mentioned
something about the "Junction" and multiverse research? We'll need to do some
more digging.

Nice work decrypting that message though.
