From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re: Passenger run from Tana Prime to Apkabar Station
Message-Id: d6069254-4182-4f96-a145-df309a992798

Just in case you missed the special note in the job description message,
I need you to pick me up in the promenade on Tana Prime before we get
going. Sorry if it's a pain, but I've just been burned before, and I'd
like to see your face before trusting my life to your ship.
