From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(3): Passenger run from Tana Prime to Apkabar Station
Message-Id: 6e1b94ec-c317-487b-a00b-d410ae6bd495

This keeps getting stranger and stranger. You have me intrigued, and
that's not easy to do. I had a friend of mine who works in the port run
a deeper scan, including network traffic analysis. He told me there's no
way your ship was under remote control--you're hardly using any
bandwidth at all. He even confirmed that the job acceptance message came
from the ship! A ship with ... no life forms.

So whatever's going on here, it's not your run of the mill passenger
scam; I'll grant you that. The second scan found a few other
clues... first of all, your ship is old as the hills. Kosaga Shipyards
has been out of business for almost half a century. But more intriguing
is the massive amount of processing power you've got loaded into it.

TODO: draw this out into another message or two

This sounds completely nuts... I tried to come up with alternate
explanations that would fit the facts, but they all sound even
crazier. The only explanation that makes sense is that your ship
is loaded up to run a machine consciousness.  Not that it makes all that
much sense that way--MC development has been illegal for nearly a
hundred years; ever since the Traxus incident. But if you're an MC,
you're not a very careful one if someone like me can spot you so easily.

Am I completely off base? I'm almost hoping there's some simple
explanation I missed some how.
