From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re(5): Passenger run from Tana Prime to Kembali Station
Message-Id: c83c2439-f4cf-475f-95a6-f15cafc3db16

Well, I wouldn't believe this if I weren't seeing it with my own
eyes. You're the real deal, a functioning machine consciousness. I've
got so many questions right now I'm not sure where to start.

I don't think I'd get very far just asking if you're only capable of
saying things like "OK". Do you have any documents or messages you
could send me that might shed some light on your situation?
