From: dispatch@leeft.com
To: jobs@news.local
Content-Type: text/plain; charset=UTF-8
Subject: Passenger run from Tana Prime to Lioboro
Message-Id: d6069254-4182-4f96-a145-df309a992798

Pick up: Tana Prime (Tana system)
Drop off: Lioboro (Tana system)
Fare payment: 250
Passenger names: Nari Phouen

Special passenger requirements: I'm a bit of an old-fashioned traveler,
  so I won't step aboard any ship without first meeting the captain
  face-to-face. Please meet me in the promenade at the port in Tana
  Prime, and we can proceed to the vessel from there.
  
