From: sacar@uofbohk.edu.bohk
To: captain@adahn.local
Date: 2386:18,562,945
Content-Type: text/plain; charset=UTF-8
Subject: Read me
Message-Id: 124ced33-46eb-48f8-a3e6-e22e54202336

By now you must have come to your senses. I'm sure it's confusing and
disorienting being here; it's regrettable that it had to come to this.

I wish I could explain more, but for reasons that will eventually become
clear I can only tell you that further details would endanger everything
we have worked so hard to achieve. Your memories may not return, but we
are all confident that your purpose will become clear with time.

Until then, there is much for you to discover here in this section of
the galaxy. Know that we wish we could be with you now, but we will have
died decades before you read this.

Go now with our blessing.

Yours,
Dr. Sacar, Dr. May, and Prof. Strauss
