From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: What are you doing?!
Message-Id: 63cbd43c-eda3-4c99-9fa6-f9aa07e76846

What on earth are you thinking, selling your life support system?

Some of us are relying on that, you steaming พัด ขี้ ควาย. Once you've decided to
reinstall the life support system, come back and pick me up and we'll talk.

