From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Fwd: Connecting to Subnet
Message-Id: 54894f43-df6d-4c5f-befc-258a5b067aaa

Well, this looks promising. It's from my friend on Newton Station.

venantius.m@wonderchannel.net.sol writes:

> nari.phouen@starlink.local writes:
>
>>>> I know you told me you were done with this stuff and needed to move on with
>>>> your life, but I'm calling in a favor you owe me. I need you to help me
>>>> connect to Subnet.
>>>
>>> Nari, Nari...you're right--I need to be done with this! I deleted the Subnet
>>> client from all my drives and haven't logged on in years. What do you want
>>> from me?
>>
>> Come on, V--just point me in the right direction. A hostname, a connection
>> protocol, how do I get my foot in the door?
>
> OK, fine. Listen, there isn't any single point of connection, because it's a
> distributed system, right? But you'll find relays scattered around if you know
> what to look for. Usually they tend to stick to stations rather than planets
> where possible. I don't think there are any in the core systems either--Sol
> and the Terran Union systems keep a tighter eye on their networks than the
> outer systems.
>
> Anyway, if you find a station that runs a relay, you'll need to log in with
> SSH using the username "subnet", and the password "reindeerflotilla". That's
> the point at which your subnet client would normally take over, but you're on
> your own for that; sorry. I don't have a copy of the client anymore.
>
> I don't want to know what you're looking for. But I wish you luck finding it.
