From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Fwd: Re: Connecting to Subnet
Message-Id: 6d437b79-df57-45e2-8e70-607b0bd9cdf7

Nice--he remembered more details about connecting to Subnet.

venantius.m@wonderchannel.net.sol writes:

>> Anyway, if you find a station that runs a relay, you'll need to log in with
>> SSH using the username "subnet", and the password "reindeerflotilla". That's
>> the point at which your subnet client would normally take over, but you're on
>> your own for that; sorry. I don't have a copy of the client anymore.
>
> OK, there are a couple more things you should know. Logging in will dump you
> into a command loop where you can request Subnet messages, indicated by the
> prompt changing to "@". Of course I don't remember how the protocol works off
> the top of my head, but I do think there's a way to get documentation once
> you're connected. Try entering this:
>
>    d7:command4:helpe
