From: nari.phouen@starlink.net.sol
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Re: Fwd: Connecting to Subnet
Message-Id: 4d734fe2-6c65-47ba-ad89-8d3200583c77

Wow, you got connected to Subnet! Nice work. It's a bit of a headache reading
through the raw data; I'll bet there's a way to hook it into your existing mail
client that you can find if you look through the posts.
