From: portal-authority@dot.gov
To: captain@adahn.local
Content-Type: text/plain; charset=UTF-8
Subject: Unauthorized portal usage

Your craft has been detected as in violation of the laws governing usage of
the portal network. Specifically, travel through a portal by an unmanned craft
is in violation of section 18b of the League of Human Worlds Transportation
Code.

This action is punishable by a fine of 2460 credits, payable at any port in
this system. Please log in to any port computer and run `port fine` in order
to pay the fine.

Until the fine is paid your ship will be prevented from any portal travel.

Portal Authority
