From: Aperture Maintenance
To: soc.sol
Subject: [ANN] Lalande Portal maintenance scheduled
Message-Id: 774dfbc5-0b09-4f2d-aca9-131573f0674c
Content-Type: text/plain; charset=UTF-8

Please be aware there is scheduled maintenance on the portal to Lalande
at the beginning of the next megasecond. The work should be wrapped up
in only 2 kiloseconds, after which the portal will return to normal
operation.

We apologize for the inconvenience.
