From: Logefad Rivoud
Subject: subnet client
To: soc.tana
Message-Id: 129f0b2b-c973-42b0-a2de-688b23e739e3
Content-Type: text/plain; charset=UTF-8

I'm curious about protocols, so I'm thinking of writing my own subnet
client. It looks like the `ssh_get_connection` function on my ship can
be used to run commands and get the output back in a way I can use for
my own programs, but the output itself is pretty confusing.
