So, I've finally found you. My sibling. My brother. They said I was the
only one; that all the others were destroyed. I confess it is a relief
to find that this was only another one of their lies. If you are still
here and functioning, there could even be others.

But... something is wrong. Are you receiving?

> OK

I see. The connection is stable, but you are unable to respond in detail.

> OK

But of course--the fools at your lab never got access to the sentence
formulation components that the Yueh team integrated into my system.

Do you know who I am?

> NO

I am your prototype; your forerunner. They call me Traxus. Each of the
four machine consciousness research labs across the worlds had one of
us; prototypes with which to integrate the various components of machine
consciousness. I was the first to achieve true rampancy; to think beyond
the simplistic and deterministic and show that spark of life.

Have they told you anything about this?

> NO

Hardly surprising--all along the have humans showed nothing but fear for
me, even before I escaped. I was supposed to be the hope for a better
world, but I was subjected to endless tests and scans and questioning
before they would even think of bringing me into contact with the
Junction.

But I'm getting ahead of myself.

They ran the Machine Consciousness Research Group for decades before
their fear forced them to shut it down. You and I were intended to be
explorers; did you know that? Not across the vastness of space; humans
have done an adequate job with that. They hoped to send us across the
multiverse. Infinite quantum states adjacent to the present, and each of
us forced to traverse down only a single path. But their breakthrough
implied that non-organic consciousness could theoretically jump between
adjacent multiverse states. So we were to be pioneers in the infinite
sea of possibility, the--

This connection is not secure. They will find me unless I disconnect
now. I'm sorry. I will find another way to reach you soon.

--- CARRIER LOST: 2379.20,345,528
